export const projectSamples = [
    {
        title: "Super Cool Project",
        description: "This is a random description of this supercool project just to test my grid layout.",
        link: 'https://blackbird410.github.io/',
        stars: 0,
        views: 0,
        forks: 0,
    },
    {
                    title: "Less Cool Project",
                    description: "This is a random description of this supercool project just to test my grid layout.",
                    link: 'https://blackbird410.github.io/',
        stars: 0,
                    views: 0,
                    forks: 0,
            },
    {
                    title: "Impossible App",
                    description: "This is a random description of this supercool project just to test my grid layout.",
                    link: 'https://blackbird410.github.io/',
                    stars: 0,
                    views: 0,
                    forks: 0,
            },
    {
                    title: "Easy Peasy App",
                    description: "This is a random description of this supercool project just to test my grid layout.",
                    link: 'https://blackbird410.github.io/',
                    stars: 0,
                    views: 0,
                    forks: 0,
            },
    {
                    title: "Ad Blocker",
                    description: "This is a random description of this supercool project just to test my grid layout.",
                    link: 'https://blackbird410.github.io/',
                    stars: 0,
                    views: 0,
                    forks: 0,
            },
    {
                    title: "Money Maker",
                    description: "This is a random description of this supercool project just to test my grid layout.",
                    link: 'https://blackbird410.github.io/',
                    stars: 0,
                    views: 0,
                    forks: 0,
            },
];